name: Azure Infrastructure Management, Deployment, and Teardown

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      teardown:
        description: 'Destroy Infrastructure (type "destroy" to confirm)'
        required: false
        default: ''

env:
  RESOURCE_GROUP: ufoalien-rg
  ACR_NAME: vflask
  LOCATION: eastus
  WEBAPP_NAME: ufoalienwebapp
  IMAGE_NAME: myapp

jobs:
  setup_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}

      - name: Create Azure Container Registry
        run: az acr create --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.ACR_NAME }} --sku Basic

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Create Azure App Service Plan
        run: |
          az appservice plan create --name ${{ env.WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --sku FREE --is-linux --location ${{ env.LOCATION }}

      - name: Create Azure Web App for Containers
        run: |
          az webapp create --resource-group ${{ env.RESOURCE_GROUP }} --plan ${{ env.WEBAPP_NAME }} --name ${{ env.WEBAPP_NAME }} --deployment-container-image-name ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
      - name: Configure Web App for HTTPS Only
        run: |
          az webapp update --name ${{ env.WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --set httpsOnly=true

      - name: Configure container settings
        run: |
          az webapp config container set --name ${{ env.WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --docker-custom-image-name ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} --docker-registry-server-url https://${{ env.ACR_NAME }}.azurecr.io


  teardown_infrastructure:
    if: ${{ github.event.inputs.teardown == 'destroy' }}
    runs-on: ubuntu-latest
    needs: setup_and_deploy
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Tear down Resource Group
        run: az group delete --name ${{ env.RESOURCE_GROUP }} --yes --no-wait
