name: Azure Infrastructure Management, Deployment, and Teardown

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      teardown:
        description: 'Destroy Infrastructure (type "destroy" to confirm)'
        required: false
        default: ''

env:
  RESOURCE_GROUP: ufoalien-rg
  ACR_NAME: vflask
  LOCATION: eastus
  WEBAPP_NAME: ufoalienwebapp
  IMAGE_NAME: myapp
  IMAGE_TAG: ${{ github.sha }}

jobs:
  setup_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resources and Deploy
        run: |
          az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}
          az acr create --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.ACR_NAME }} --sku Basic
          az acr login --name ${{ env.ACR_NAME }}
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          az appservice plan create --name ${{ env.WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --sku FREE --is-linux --location ${{ env.LOCATION }}
          az webapp create --resource-group ${{ env.RESOURCE_GROUP }} --plan ${{ env.WEBAPP_NAME }} --name ${{ env.WEBAPP_NAME }} --deployment-container-image-name ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          az webapp update --name ${{ env.WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --set httpsOnly=true

  teardown_infrastructure:
    if: ${{ github.event.inputs.teardown == 'destroy' }}
    runs-on: ubuntu-latest
    needs: setup_and_deploy
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: az group delete --name ${{ env.RESOURCE_GROUP }} --yes --no-wait
